app:
  name: CurrencyExchangeApp
  port: :8080

database:
  Dsn: root:root@tcp(127.0.0.1:3306)/gin_gorm_learn?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenConns: 114

redis:
  Addr: localhost:6379
  DB: 0
  Password: ''